version: "3.0"

services:
    redis:
        ports:
        - "6379:6379"

    bot:
        environment:
        - NODE_ENV=production
        - SERVER_PROTOCOL=https
        - SERVER_URL=server
        - SERVER_PORT=8080

    server:
        environment:
        - NODE_ENV=production
        - PORT=8080
        - REDIS_URL=redis
        - REDIS_PORT=6379
        ports:
        - "8080:8080"